version: "3.8"
services:
 gestionCinema:
  image: mysql:8
  cap_add:
   - SYS_NICE
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=Admin123
  ports:
   - "3306:3306"
  volumes:
   - ./db:/var/lib/mysql
volumes:
 gestionCinema:
  driver: local
